import 'dotenv/config';
import { ConfigService } from '@nestjs/config';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { RepositoryService } from '../src/database/repository.service';

const collections = ['vehicles','trips','trip_runtime','trip_settlements','mqtt_logs','command_history'];
const workDir=resolve(process.cwd(),'..','.cloudbase-admin'); const statePath=resolve(workDir,'tianmashan-migration-state.json');
type State={env:string;backupAt?:string;backupDir?:string;dryRunAt?:string;dryRun?:Record<string,Summary>}; type Summary={count:number;missingScenicAreaId:number;demoCount:number;missingDemoFlag:number;amountCents:number};
function envId(){return String(process.env.CLOUDBASE_ENV_ID||'').trim();}
function assertEnvironment(){const env=envId();if(!env)throw new Error('缺少 CLOUDBASE_ENV_ID');if(/prod/i.test(env)&&process.env.ALLOW_PRODUCTION_MIGRATION!=='true')throw new Error('检测到生产环境；默认禁止迁移。生产操作必须另行明确授权并设置 ALLOW_PRODUCTION_MIGRATION=true');if(!/(dev|test|stage|staging)/i.test(env)&&process.env.ALLOW_NON_DEV_MIGRATION!=='true')throw new Error('环境名称未明确标识为 dev/test/staging，已拒绝执行');}
async function all(db:any,name:string){const rows:any[]=[];const size=100;for(let skip=0;;skip+=size){const result=await db.collection(name).skip(skip).limit(size).get();const page=Array.isArray(result?.data)?result.data:[];rows.push(...page);if(page.length<size)break;}return rows;}
function isDemo(row:any){const values=[row._id,row.id,row.orderNo,row.tripNo,row.ugvID,row.vehicleNo].map((value)=>String(value||''));return Boolean(row.isDemo)||values.some((value)=>/^(demo|sample|test|mock)[-_]?/i.test(value));}
function amount(row:any){const direct=Number(row.originalAmountCents??row.totalAmountCents??row.amountCents);if(Number.isFinite(direct))return Math.round(direct);const yuan=Number(row.totalFee??row.actualFee??row.amount??row.total??row.fee?.total??row.cost);return Number.isFinite(yuan)?Math.round(yuan*100):0;}
function summarize(rows:any[]):Summary{return{count:rows.length,missingScenicAreaId:rows.filter((row)=>!row.scenicAreaId).length,demoCount:rows.filter(isDemo).length,missingDemoFlag:rows.filter((row)=>row.isDemo===undefined&&isDemo(row)).length,amountCents:rows.reduce((sum,row)=>sum+amount(row),0)};}
async function readState():Promise<State>{try{return JSON.parse(await readFile(statePath,'utf8'));}catch{return{env:envId()};}}
async function saveState(state:State){await mkdir(workDir,{recursive:true});await writeFile(statePath,JSON.stringify(state,null,2),'utf8');}
async function backup(db:any){const stamp=new Date().toISOString().replace(/[:.]/g,'-');const dir=resolve(workDir,'backups',stamp);await mkdir(dir,{recursive:true});const summary:Record<string,Summary>={};for(const name of collections){const rows=await all(db,name);summary[name]=summarize(rows);await writeFile(resolve(dir,`${name}.json`),JSON.stringify(rows,null,2),'utf8');}const state:State={env:envId(),backupAt:new Date().toISOString(),backupDir:dir};await saveState(state);console.log(JSON.stringify({mode:'backup',env:envId(),dir,summary},null,2));}
async function dryRun(db:any){const state=await readState();if(state.env!==envId()||!state.backupAt||!state.backupDir)throw new Error('必须先对同一环境执行 MIGRATION_MODE=backup');const summary:Record<string,Summary>={};for(const name of collections)summary[name]=summarize(await all(db,name));state.dryRunAt=new Date().toISOString();state.dryRun=summary;await saveState(state);console.log(JSON.stringify({mode:'dry-run',env:envId(),targetScenicAreaId:'tianmashan',wouldUpdate:Object.fromEntries(Object.entries(summary).map(([name,value])=>[name,{scenicAreaId:value.missingScenicAreaId,isDemo:value.missingDemoFlag}])),summary},null,2));}
async function apply(db:any){const state=await readState();if(state.env!==envId()||!state.backupAt||!state.dryRunAt||!state.dryRun)throw new Error('必须依次对同一环境完成 backup 和 dry-run');if(process.env.MIGRATION_CONFIRM!=='APPLY_TIANMASHAN')throw new Error('apply 需要设置 MIGRATION_CONFIRM=APPLY_TIANMASHAN');const before=state.dryRun;const rowsByCollection:Record<string,any[]>={};for(const name of collections){const rows=await all(db,name);rowsByCollection[name]=rows;const current=summarize(rows);const expected=before[name];if(!expected||current.count!==expected.count||current.amountCents!==expected.amountCents||current.missingScenicAreaId!==expected.missingScenicAreaId||current.missingDemoFlag!==expected.missingDemoFlag)throw new Error(`${name} 在 dry-run 后发生变化，请重新执行 backup 和 dry-run`);}const updated:Record<string,number>={};for(const name of collections){const rows=rowsByCollection[name];updated[name]=0;for(const row of rows){const needsScenic=!row.scenicAreaId;const needsDemoFlag=row.isDemo===undefined&&isDemo(row);if(!needsScenic&&!needsDemoFlag)continue;const id=String(row._id||row.id||'');if(!id)throw new Error(`${name} 中存在无主键记录`);const patch:any={migrationVersion:'tianmashan-v1',migrationAt:new Date().toISOString()};if(needsScenic)patch.scenicAreaId='tianmashan';if(needsDemoFlag)patch.isDemo=true;await db.collection(name).doc(id).update(patch);updated[name]++;}}
  const after:Record<string,Summary>={};for(const name of collections)after[name]=summarize(await all(db,name));for(const name of collections){if(after[name].count!==before[name].count||after[name].amountCents!==before[name].amountCents||after[name].missingScenicAreaId!==0||after[name].missingDemoFlag!==0)throw new Error(`${name} 迁移核对失败，请停止发布并使用备份排查`);}console.log(JSON.stringify({mode:'apply',env:envId(),updated,before,after,deleted:0},null,2));}
async function main(){if(process.env.DATA_DRIVER!=='cloudbase')throw new Error('请显式设置 DATA_DRIVER=cloudbase');assertEnvironment();const repository=new RepositoryService(new ConfigService());repository.initialize();const db=repository.rawDatabase();const mode=String(process.env.MIGRATION_MODE||'');if(mode==='backup')return backup(db);if(mode==='dry-run')return dryRun(db);if(mode==='apply')return apply(db);throw new Error('MIGRATION_MODE 必须是 backup、dry-run 或 apply');}
main().catch((error)=>{console.error('[migrate-tianmashan]',error instanceof Error?error.message:error);process.exitCode=1;});
