<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { ElMessage } from 'element-plus';
import { api, isMockMode } from '@/api';
import { useAppStore } from '@/stores/app';
import HealthBadge from '@/components/HealthBadge.vue';
import type { HealthLevel, VehicleCommand } from '@/types/domain';
import { shanghaiTime } from '@/utils/format';
const appStore = useAppStore(); const commands = ref<VehicleCommand[]>([]); const loading = ref(false); const health = computed(() => appStore.health); const healthyCount = computed(() => health.value?.components.filter((item) => item.level === 'healthy').length || 0);
async function load() { loading.value = true; try { await appStore.refreshHealth(); commands.value = await api.vehicleCommands(appStore.selectedScenicAreaId); } finally { loading.value = false; } }
async function scenario(level: HealthLevel) { if (!api.setMockHealthScenario) return; appStore.health = await api.setMockHealthScenario(level); ElMessage.success(`已切换为${level === 'healthy' ? '健康' : level === 'degraded' ? '降级' : '故障'}演示状态`); }
watch(() => appStore.selectedScenicAreaId, load, { immediate: true });
</script>
<template><div class="page-stack" v-loading="loading"><section class="system-hero" :class="`is-${health?.level || 'degraded'}`"><div><p class="eyebrow">SYSTEM READINESS</p><h2>{{ health?.summary || '正在聚合系统状态' }}</h2><p>HTTP 可访问只代表存活；MQTT 断开、数据库不可用或车辆心跳异常都会降低就绪状态。</p></div><div class="health-score"><strong>{{ healthyCount }}/{{ health?.components.length || 0 }}</strong><span>组件健康</span><small>{{ shanghaiTime(health?.checkedAt) }}</small></div></section><section class="panel" v-if="isMockMode"><div class="demo-scenario"><div><strong>状态演示控制器</strong><span>仅改变 Mock 数据，用于评审状态栏与诊断交互</span></div><el-button-group><el-button type="success" plain @click="scenario('healthy')">健康</el-button><el-button type="warning" plain @click="scenario('degraded')">降级</el-button><el-button type="danger" plain @click="scenario('critical')">故障</el-button></el-button-group></div></section><section class="health-grid" v-if="health"><article v-for="component in health.components" :key="component.key" class="health-card" :class="`is-${component.level}`"><div class="health-card-head"><HealthBadge :level="component.level" /><span v-if="component.latencyMs">{{ component.latencyMs }} ms</span></div><h3>{{ component.name }}</h3><p>{{ component.message }}</p><small>检查于 {{ shanghaiTime(component.checkedAt) }}</small></article></section><section class="two-column"><article class="panel"><div class="panel-title"><div><h2>当前事件</h2><p>需要运营人员关注的聚合异常</p></div></div><div class="incident-list" v-if="health?.incidents.length"><div v-for="incident in health.incidents" :key="incident.id" class="incident-item"><HealthBadge :level="incident.level" /><div><strong>{{ incident.title }}</strong><p>{{ incident.detail }}</p><small>{{ shanghaiTime(incident.occurredAt) }}</small></div></div></div><el-empty v-else description="当前没有系统事件" :image-size="86" /></article><article class="panel"><div class="panel-title"><div><h2>模拟指令回执</h2><p>后台指令不会发布至 MQTT Broker</p></div><el-tag type="warning">SIMULATED</el-tag></div><el-table :data="commands.slice(0,6)" size="small" empty-text="尚无模拟指令"><el-table-column prop="commandKey" label="指令" min-width="120" /><el-table-column prop="vehicleId" label="车辆" min-width="110" /><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="row.status === 'acked' ? 'success' : row.status === 'timed_out' ? 'danger' : 'primary'" size="small">{{ row.status }}</el-tag></template></el-table-column><el-table-column label="时间" width="145"><template #default="{ row }">{{ shanghaiTime(row.updatedAt) }}</template></el-table-column></el-table></article></section><section class="panel"><div class="panel-title"><div><h2>状态判定规则</h2><p>第一期健康聚合验收契约</p></div></div><div class="rule-grid"><div><b>健康</b><span>API、数据库、MQTT 均正常，车辆心跳与指令失败率在阈值内。</span></div><div><b>降级</b><span>核心业务仍可查询，但存在 MQTT 断开、部分车辆失联或依赖延迟。</span></div><div><b>故障</b><span>数据库、认证或多个核心依赖不可用，需要立即干预。</span></div></div></section></div></template>
