import { randomUUID } from 'node:crypto';
import type { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import * as argon2 from 'argon2';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { AppModule } from '../src/app.module';
import { configureApp } from '../src/bootstrap';
import { RepositoryService } from '../src/database/repository.service';
import { passwordHashOptions } from '../src/auth/auth.service';

describe('admin API integration', () => {
  let app: INestApplication; let repository: RepositoryService; let agent: ReturnType<typeof request.agent>; let csrf='';
  const username=`admin-${randomUUID().slice(0,8)}`; const password=`Test-${randomUUID()}-A1a`;
  beforeAll(async()=>{const moduleRef=await Test.createTestingModule({imports:[AppModule]}).compile();app=configureApp(moduleRef.createNestApplication());await app.init();repository=moduleRef.get(RepositoryService);const now=new Date().toISOString();await repository.createAdmin({id:randomUUID(),username,displayName:'测试管理员',role:'super_admin',passwordHash:await argon2.hash(password,passwordHashOptions),mustChangePassword:false,active:true,createdAt:now,updatedAt:now});agent=request.agent(app.getHttpServer());});
  afterAll(async()=>{await app.close();});

  it('rejects unauthenticated access with standard envelope',async()=>{const response=await request(app.getHttpServer()).get('/api/admin/v1/scenic-areas');expect(response.status).toBe(401);expect(response.body).toMatchObject({code:'HTTP_401',data:null});expect(response.body.requestId).toBeTruthy();});
  it('logs in with an HttpOnly session and returns CSRF token',async()=>{const response=await agent.post('/api/admin/v1/auth/login').send({username,password});expect(response.status).toBe(201);expect(response.headers['set-cookie']?.join(';')).toContain('HttpOnly');expect(response.body.data.user.role).toBe('super_admin');csrf=response.body.data.csrfToken;expect(csrf).toBeTruthy();});
  it('requires CSRF for mutations',async()=>{const response=await agent.post('/api/admin/v1/orders/trip-1/notes').set('x-omo-scenic-area-id','tianmashan').send({content:'未携带 CSRF'});expect(response.status).toBe(403);expect(response.body.message).toMatch(/CSRF/);});
  it('rejects cross-scenic entity IDs',async()=>{const response=await agent.get('/api/admin/v1/orders/trip-demo').set('x-omo-scenic-area-id','tianmashan');expect(response.status).toBe(404);});
  it('appends an internal order note',async()=>{const response=await agent.post('/api/admin/v1/orders/trip-1/notes').set('x-omo-scenic-area-id','tianmashan').set('x-csrf-token',csrf).send({content:'已由测试确认车辆状态'});expect(response.status).toBe(201);expect(response.body.data.noteCount).toBe(1);expect(response.body.data.notes[0].content).toContain('测试确认');});
  it('adds immutable adjustment rows idempotently and reverses by a new row',async()=>{const key=randomUUID();const body={type:'credit',amountCents:200,reason:'测试停车计时补偿',idempotencyKey:key};const first=await agent.post('/api/admin/v1/finance/settlements/settle-1/adjustments').set('x-omo-scenic-area-id','tianmashan').set('x-csrf-token',csrf).send(body);expect(first.status).toBe(201);expect(first.body.data.originalAmountCents).toBe(3275);expect(first.body.data.effectiveAmountCents).toBe(3075);const duplicate=await agent.post('/api/admin/v1/finance/settlements/settle-1/adjustments').set('x-omo-scenic-area-id','tianmashan').set('x-csrf-token',csrf).send(body);expect(duplicate.body.data.adjustments).toHaveLength(1);const adjustmentId=first.body.data.adjustments[0].id;const reversed=await agent.post(`/api/admin/v1/finance/settlements/settle-1/adjustments/${adjustmentId}/reverse`).set('x-omo-scenic-area-id','tianmashan').set('x-csrf-token',csrf).send({reason:'测试撤销补偿流水',idempotencyKey:randomUUID()});expect(reversed.body.data.originalAmountCents).toBe(3275);expect(reversed.body.data.effectiveAmountCents).toBe(3275);expect(reversed.body.data.adjustments).toHaveLength(2);expect(reversed.body.data.adjustments[1].reversedAdjustmentId).toBe(adjustmentId);});
  it('rejects reused idempotency keys with different payloads',async()=>{const financeKey=randomUUID();const firstFinance={type:'charge',amountCents:100,reason:'测试追加停车费',idempotencyKey:financeKey};expect((await agent.post('/api/admin/v1/finance/settlements/settle-1/adjustments').set('x-omo-scenic-area-id','tianmashan').set('x-csrf-token',csrf).send(firstFinance)).status).toBe(201);expect((await agent.post('/api/admin/v1/finance/settlements/settle-1/adjustments').set('x-omo-scenic-area-id','tianmashan').set('x-csrf-token',csrf).send({...firstFinance,amountCents:101})).status).toBe(400);const commandKey=randomUUID();const firstCommand={scenicAreaId:'tianmashan',vehicleId:'veh-0008',commandKey:'query_status',params:{},reason:'测试查询车辆状态',idempotencyKey:commandKey};expect((await agent.post('/api/admin/v1/vehicle-commands').set('x-omo-scenic-area-id','tianmashan').set('x-csrf-token',csrf).send(firstCommand)).status).toBe(201);expect((await agent.post('/api/admin/v1/vehicle-commands').set('x-omo-scenic-area-id','tianmashan').set('x-csrf-token',csrf).send({...firstCommand,reason:'测试查询另一请求'})).status).toBe(400);});
  it('creates only simulated whitelisted commands and rejects raw fields',async()=>{const raw=await agent.post('/api/admin/v1/vehicle-commands').set('x-omo-scenic-area-id','tianmashan').set('x-csrf-token',csrf).send({scenicAreaId:'tianmashan',vehicleId:'veh-0008',commandKey:'query_status',params:{},reason:'测试原始 topic 拒绝',idempotencyKey:randomUUID(),topic:'ugv/any/platform'});expect(raw.status).toBe(400);const created=await agent.post('/api/admin/v1/vehicle-commands').set('x-omo-scenic-area-id','tianmashan').set('x-csrf-token',csrf).send({scenicAreaId:'tianmashan',vehicleId:'veh-0008',commandKey:'query_status',params:{},reason:'测试查询车辆状态',idempotencyKey:randomUUID()});expect(created.status).toBe(201);expect(created.body.data).toMatchObject({simulated:true,status:'sent'});await new Promise((resolve)=>setTimeout(resolve,1000));const list=await agent.get('/api/admin/v1/vehicle-commands?scenicAreaId=tianmashan').set('x-omo-scenic-area-id','tianmashan');expect(list.body.data[0].status).toBe('acked');});
  it('keeps simulated command idempotency scoped and records timeout without MQTT',async()=>{const key=randomUUID();const input={scenicAreaId:'tianmashan',vehicleId:'veh-0008',commandKey:'query_status',params:{simulateTimeout:true},reason:'测试模拟回执超时',idempotencyKey:key};const first=await agent.post('/api/admin/v1/vehicle-commands').set('x-omo-scenic-area-id','tianmashan').set('x-csrf-token',csrf).send(input);const duplicate=await agent.post('/api/admin/v1/vehicle-commands').set('x-omo-scenic-area-id','tianmashan').set('x-csrf-token',csrf).send(input);expect(duplicate.body.data.id).toBe(first.body.data.id);const collision=await agent.post('/api/admin/v1/vehicle-commands').set('x-omo-scenic-area-id','tianmashan').set('x-csrf-token',csrf).send({...input,vehicleId:'veh-0009'});expect(collision.status).toBe(400);const rawParams=await agent.post('/api/admin/v1/vehicle-commands').set('x-omo-scenic-area-id','tianmashan').set('x-csrf-token',csrf).send({...input,idempotencyKey:randomUUID(),params:{topic:'ugv/raw'}});expect(rawParams.status).toBe(400);await new Promise((resolve)=>setTimeout(resolve,1000));const list=await agent.get('/api/admin/v1/vehicle-commands?scenicAreaId=tianmashan').set('x-omo-scenic-area-id','tianmashan');expect(list.body.data.find((item:any)=>item.id===first.body.data.id).status).toBe('timed_out');});
  it('shows degraded when MQTT health is unavailable instead of false healthy',async()=>{const response=await agent.get('/api/admin/v1/system/health?scenicAreaId=tianmashan').set('x-omo-scenic-area-id','tianmashan');expect(response.status).toBe(200);expect(response.body.data.level).not.toBe('healthy');expect(response.body.data.components.find((item:any)=>item.key==='mqtt').level).toBe('degraded');});
  it('enforces forced password change on bootstrap-style users',async()=>{const forcedUser=`first-${randomUUID().slice(0,8)}`;const forcedPassword=`First-${randomUUID()}-A1a`;const now=new Date().toISOString();await repository.createAdmin({id:randomUUID(),username:forcedUser,displayName:'首次登录管理员',role:'super_admin',passwordHash:await argon2.hash(forcedPassword,passwordHashOptions),mustChangePassword:true,active:true,createdAt:now,updatedAt:now});const forcedAgent=request.agent(app.getHttpServer());const login=await forcedAgent.post('/api/admin/v1/auth/login').send({username:forcedUser,password:forcedPassword});const forcedCsrf=login.body.data.csrfToken;expect((await forcedAgent.get('/api/admin/v1/orders')).status).toBe(403);const nextPassword=`Next-${randomUUID()}-A1a`;expect((await forcedAgent.post('/api/admin/v1/auth/password').set('x-csrf-token',forcedCsrf).send({currentPassword:forcedPassword,newPassword:nextPassword})).status).toBe(201);expect((await forcedAgent.get('/api/admin/v1/orders')).status).toBe(200);});
  it('rate-limits repeated failed logins',async()=>{const login=request(app.getHttpServer());for(let index=0;index<5;index++){expect((await login.post('/api/admin/v1/auth/login').send({username:'blocked-user',password:'wrong-pass'})).status).toBe(401);}const blocked=await login.post('/api/admin/v1/auth/login').send({username:'blocked-user',password:'wrong-pass'});expect(blocked.status).toBe(429);expect(blocked.body.code).toBe('AUTH_RATE_LIMITED');});
  it('deletes the server session and expires the cookie on logout',async()=>{const response=await agent.post('/api/admin/v1/auth/logout').set('x-csrf-token',csrf);expect(response.status).toBe(201);expect(response.headers['set-cookie']?.join(';')).toMatch(/Expires=Thu, 01 Jan 1970/);expect((await agent.get('/api/admin/v1/orders')).status).toBe(401);});
});
